### PR TITLE
Fix utf8 support for dataUri base64

### LINKED ISSUE #13: Garbled characters appear when sourcesContent contains Chinese characters
https://github.com/lydell/source-map-resolve/blob/858cd9e2ecce25427761b8be616cabf704c69316/lib/source-map-resolve-node.js#L101

`atob` equals
```js
const atob = (encodedString) => Buffer.from(encodedString, 'base64').toString('latin1')
```

But we should use utf-8 rather than binary:
```js
(encodedString) => Buffer.from(encodedString, 'base64').toString()
// or
(encodedString) => Buffer.from(encodedString, 'base64').toString('utf8')
```

see https://github.com/ng-packagr/ng-packagr/issues/1475

I can take a pr later to solve the character set problem.

### PR DESCRIPTION
**Pull request by lydell**
Continuation of #14. Closes #13.

@xiaoxiangmoe I failed to push to your branch so I’m opening a new PR.

### CODE REVIEW

File: lib/source-map-resolve-node.js [hunk 1]
```diff
@@ -71,8 +71,45 @@ function resolveSourceMapSync(code, codeUrl, read) {
...
+  return arr
+}
+
+function decodeBase64String(b64) {
+  if (typeof TextDecoder === "undefined" || typeof Uint8Array === "undefined") {
+    return atob(b64)
+  }
+  var buf = base64ToBuf(b64);
+  // Note: `decoder.decode` method will throw a `DOMException` with the
+  // `"EncodingError"` value when an coding error is found.
```
Comment (lydell) [inline lib/source-map-resolve-node.js]: I need to catch this error and add a test for it.

File: lib/source-map-resolve-node.js [hunk 2]
```diff
@@ -71,8 +71,45 @@ function resolveSourceMapSync(code, codeUrl, read) {
...
+  var arr = new Uint8Array(len)
+  for (var i = 0; i < len; i++) {
+    arr[i] = binStr.charCodeAt(i)
+  }
+  return arr
+}
+
+function decodeBase64String(b64) {
+  if (typeof TextDecoder === "undefined" || typeof Uint8Array === "undefined") {
+    return atob(b64)
```
Comment (lydell) [inline lib/source-map-resolve-node.js]: I removed the warning because I’m worried it would spam the console. I don’t think many people will end up here though.

File: lib/source-map-resolve-node.js (hunk 1 above)
Comment (lydell) [reply lib/source-map-resolve-node.js]: Or maybe it’s better to use `fatal: false`?

Comment (lydell) [reply lib/source-map-resolve-node.js]: @xiaoxiangmoe what do you think? Are utf8 errors commonly generated by tools? What is more helpful to the user – errors or replacement characters?

Comment (xiaoxiangmoe) [reply lib/source-map-resolve-node.js]: I think `fatal: true` is better for users. It doesn't happen very often, but once it does, it's easier to spot the problem if an error is throw.

Comment (lydell) [reply lib/source-map-resolve-node.js]: Ok. Do you know how I can create a base64 with a utf8 error in it, so I can write a test?

Comment (xiaoxiangmoe) [reply lib/source-map-resolve-node.js]: We might construct an lantin1-encoded base64(with some non ascii char in 0xA0-0xFF), then read it in utf8, and it may raise a utf8 error.

Comment (xiaoxiangmoe) [reply lib/source-map-resolve-node.js]: I'm sorry, my computer is out of power, I can't easily test it with my mobile phone now. We might find a typical illegal utf-8 sequence and write the test as lantin 1

Comment (xiaoxiangmoe) [reply lib/source-map-resolve-node.js]: https://stackoverflow.com/questions/1301402/example-invalid-utf8-string

Comment (lydell) [reply lib/source-map-resolve-node.js]: I found through trial and error that `abc` results in invalid utf8. 🤷‍♂

**Comment by lydell** [comment]
@xiaoxiangmoe If this looks good to you I can merge and make a release in a couple of days.
